Removed path number from path replacement
amaurremi/dot-calculus pull request #10
Opened 2019-06-11 22:13 UTC by luuuwang7

2019-06-12 04:59 UTC, amaurremi requested changes
This is great, thank you very much for simplifying the proof! I added some minor comments, please let me know if you have any questions.

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/Replacement.v
> +    (**try solve [simpl; assert (numpaths U = numpaths (open_rec_typ_p n0 r0 U))
let's just remove this code

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/Replacement.v
> +(*
let's remove this commented out code

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/PreciseTyping.v
> +  inversions H. destruct_all. invert_repl.
dangling space

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/Replacement.v
> +  introv Hs. dependent induction Hs.
dangling space

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/Replacement.v
> +(**;
let's remove this code

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/Replacement.v
> +(**
let's remove this

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/ReplacementTyping.v
> +(**
let's remove this

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/ReplacementTyping.v
> +Lemma pf_sngl_sel_unique: forall G p q q0 r0 bs0 bs,
This lemma reasons about precise typing. Could we move it to `PreciseFlow.v`?

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/ReplacementTyping.v
> +  intros. destruct (sel_sub_fields _ _ _ _ H2) as [bs1 [Hl | Hl]].
to reduce the number of unnamed hypotheses, let's name the hypotheses at the point of `intros`. Here, we could do `introv Hi Hq Hq0 Heq`.

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/ReplacementTyping.v
> +Qed.
the two cases in this proof are almost identical so we could use some automation, e.g.
```
destruct (sel_sub_fields _ _ _ _ Heq) as [? [-> | ->]];
    [pose proof (pf_sngl_flds_elim _ Hi Hq Hq0) as ->
    | pose proof (pf_sngl_flds_elim _ Hi Hq0 Hq) as ->]; eauto;
      rewrite field_sel_nil in *;    
      apply (pf_T_unique Hi Hq) in Hq0 as [= ->];
     apply sel_fields_equal in Heq as ->; auto. 
```

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/ReplacementTyping.v
> +  - inversions H0. destruct (H _ _ _ _ H7 H1 H2 H3); eauto.
Could we use the `invert_repl` tactic instead of `inversions H0`? That way we would reduce the uses of unnamed hypotheses. Same for other cases in this lemma.

2019-06-12 04:59 UTC, amaurremi commented on src/extensions/paths/ReplacementTyping.v
> +    * destruct (H _ _ _ _ H9 H1 H2 H3); eauto.
If we add a `subst` before the `eauto`, we could go down to one case; `subst` also allows us to avoid having to manually rewrite simple equalities since automatically rewrites all equalities for variables. Perhaps this holds for later cases as well.

2019-06-12 12:35 UTC, olhotak commented
Thank you, @luuuwang7 , this is great.

Also thank you @amaurremi for the suggestions to clean things up further.

Please remove the last line of Definitions.v (Ltac omega). omega is used to reason about arithmetic (e.g. n + numpaths T) and we're not doing that anymore.

I looked through the changes and aside from these suggestions, it all looks good to me and can be merged.

2019-06-12 18:09 UTC, olhotak commented
@amaurremi pf_sngl_sel_unique depends on pf_sngl_flds_elim. Would it be possible to also move pf_sngl_flds_elim and pf_sngl_fld_elim to PreciseFlow?

2019-06-13 15:41 UTC, amaurremi commented
Yes, you're right, moved the necessary lemmas to PreciseFlow.

2019-06-13 20:09 UTC, merged